export const SCHEMES_DATA = [
  // SIDBI LOANS
  { scheme_name: "EXPRESS Loan", min_amount_cr: 0.01, max_amount_cr: 1.0, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION"], is_for_new_unit: false, key_benefit_keywords: ["FAST_APPROVAL", "100%_FINANCING_W_FD"], loan_type: "MACHINERY", max_tenure_yrs: 5 },
  { scheme_name: "SPEED Loan", min_amount_cr: 0.01, max_amount_cr: 15.0, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION"], is_for_new_unit: false, key_benefit_keywords: ["HIGH_LIMIT", "MINIMAL_COLLATERAL", "LONG_TENURE"], loan_type: "MACHINERY", max_tenure_yrs: 7 },
  { scheme_name: "ATOM", min_amount_cr: 0.01, max_amount_cr: 1.0, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION"], is_for_new_unit: false, key_benefit_keywords: ["TReDS_FOCUS", "IMMEDIATE_OFFER", "100%_FINANCING"], loan_type: "MACHINERY", max_tenure_yrs: 5 },
  { scheme_name: "ARISE", min_amount_cr: 0.01, max_amount_cr: 50.0, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION", "CAPEX_FACTORY_CONSTRUCTION", "PROJECT_EXPANSION", "CAPEX_SOLAR"], is_for_new_unit: false, key_benefit_keywords: ["HIGH_LIMIT", "SUSTAINABLE", "COVERS_LAND"], loan_type: "PROJECT_LOAN", max_tenure_yrs: 7 },
  { scheme_name: "STHAPAN", min_amount_cr: 0.01, max_amount_cr: 50.0, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION", "CAPEX_FACTORY_CONSTRUCTION", "PROJECT_SETUP", "CAPEX_SOLAR"], is_for_new_unit: true, key_benefit_keywords: ["HIGH_LIMIT", "GREENFIELD_FOCUS", "COVERS_LAND"], loan_type: "PROJECT_LOAN", max_tenure_yrs: 7 },
  { scheme_name: "UBHARTE SITAARE", min_amount_cr: 0.01, max_amount_cr: 30.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["PROJECT_MODERNIZATION", "EXPORT_POTENTIAL"], is_for_new_unit: false, key_benefit_keywords: ["PERFORMANCE_INCENTIVES", "GLOBAL_GROWTH", "TECHNOLOGY_UPGRADE"], loan_type: "PROJECT_LOAN", max_tenure_yrs: 7 },
  { scheme_name: "ARJANA", min_amount_cr: 0.01, max_amount_cr: 3.0, target_demographics: ["WOMAN_PROMOTER"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION", "PROJECT_EXPANSION"], is_for_new_unit: null, key_benefit_keywords: ["100%_MACHINERY_FINANCING", "SOFT_TERMS", "CGTME_FEE_INCENTIVE"], loan_type: "PROJECT_LOAN", max_tenure_yrs: 7 },
  { scheme_name: "SAATH", min_amount_cr: 0.01, max_amount_cr: 3.0, target_demographics: ["SC_ST_PROMOTER"], target_sectors: ["MANUFACTURING", "SERVICE", "ALL"], target_purpose: ["CAPEX_MACHINERY_ACQUISITION", "PROJECT_EXPANSION"], is_for_new_unit: null, key_benefit_keywords: ["100%_MACHINERY_FINANCING", "SOFT_TERMS", "CGTME_FEE_INCENTIVE"], loan_type: "PROJECT_LOAN", max_tenure_yrs: 7 },
  { scheme_name: "MORE", min_amount_cr: 0.01, max_amount_cr: 5.0, target_demographics: ["ALL"], target_sectors: ["SERVICE", "TOURISM_HOSPITALITY"], target_purpose: ["PROJECT_MODERNIZATION", "INTERIOR_RENOVATION"], is_for_new_unit: false, key_benefit_keywords: ["SWIFT_SANCTIONS", "FLEXIBLE_REPAYMENT"], loan_type: "THEMATIC", max_tenure_yrs: 8 },
  { scheme_name: "CASH DEFENCE", min_amount_cr: 0.01, max_amount_cr: 20.0, target_demographics: ["ALL"], target_sectors: ["DEFENCE_SECTOR"], target_purpose: ["PURCHASE_ORDER_FINANCING"], is_for_new_unit: null, key_benefit_keywords: ["100%_PO_FINANCING", "STANDBY_CREDIT", "CUSTOMIZED_REPAYMENT"], loan_type: "THEMATIC", max_tenure_yrs: 5 },
  { scheme_name: "CASH RXIL", min_amount_cr: 0.01, max_amount_cr: 25.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["PURCHASE_ORDER_FINANCING"], is_for_new_unit: false, key_benefit_keywords: ["RXIL_TReDS_FOCUS", "HIGH_LIMIT", "FAST_DISBURSAL"], loan_type: "THEMATIC", max_tenure_yrs: 0.5 },
  { scheme_name: "EDGE", min_amount_cr: 0.01, max_amount_cr: 3.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["CAPEX_DG_SET"], is_for_new_unit: false, key_benefit_keywords: ["CLEANER_ENERGY", "LOWER_PROMOTER_CONTRIBUTION"], loan_type: "THEMATIC", max_tenure_yrs: 5 },
  { scheme_name: "AGRI-AI", min_amount_cr: 0.01, max_amount_cr: 50.0, target_demographics: ["ALL"], target_sectors: ["AGRO_PROCESSING"], target_purpose: ["PROJECT_EXPANSION", "WORKING_CAPITAL_GENERAL", "COLD_STORAGE", "LOGISTICS"], is_for_new_unit: null, key_benefit_keywords: ["COMPOSITE_OPTION", "FPO_ELIGIBILITY", "80%_PROJECT_FINANCE"], loan_type: "THEMATIC", max_tenure_yrs: 7 },
  { scheme_name: "Green Finance Scheme (GFS)", min_amount_cr: 0.01, max_amount_cr: 50.0, target_demographics: ["ALL"], target_sectors: ["GREEN_VALUE_CHAIN"], target_purpose: ["PROJECT_SETUP", "PROJECT_EXPANSION", "GREEN_VALUE_CHAIN"], is_for_new_unit: null, key_benefit_keywords: ["SUSTAINABLE_FOCUS", "HIGH_LIMIT"], loan_type: "GREEN", max_tenure_yrs: 10 },
  { scheme_name: "4E Scheme", min_amount_cr: 0.01, max_amount_cr: 10.0, target_demographics: ["ALL"], target_sectors: ["GREEN_VALUE_CHAIN", "ALL"], target_purpose: ["ENERGY_EFFICIENCY", "CAPEX_MACHINERY_ACQUISITION"], is_for_new_unit: false, key_benefit_keywords: ["100%_FINANCING", "ENERGY_EFFICIENCY"], loan_type: "GREEN", max_tenure_yrs: 5 },
  { scheme_name: "Electric Vehicle Scheme", min_amount_cr: 0.01, max_amount_cr: 20.0, target_demographics: ["ALL"], target_sectors: ["GREEN_VALUE_CHAIN", "SERVICE", "TRANSPORT"], target_purpose: ["CAPEX_EV_INFRA", "VEHICLE_FINANCING"], is_for_new_unit: null, key_benefit_keywords: ["ECO_FRIENDLY", "INFRASTRUCTURE_FUNDING"], loan_type: "GREEN", max_tenure_yrs: 5 },
  { scheme_name: "SWIFT", min_amount_cr: 0.01, max_amount_cr: 3.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["WORKING_CAPITAL_GENERAL"], is_for_new_unit: false, key_benefit_keywords: ["OVERDRAFT", "QUICK_DISBURSAL"], loan_type: "WORKING_CAPITAL", max_tenure_yrs: 3 },
  { scheme_name: "STEP", min_amount_cr: 0.01, max_amount_cr: 3.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["WORKING_CAPITAL_GENERAL"], is_for_new_unit: false, key_benefit_keywords: ["TERM_LOAN", "ENHANCE_PRODUCTION"], loan_type: "WORKING_CAPITAL", max_tenure_yrs: 3 },
  { scheme_name: "Secured Business Loan (SBL)", min_amount_cr: 0.01, max_amount_cr: 10.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["GENERAL_BUSINESS_NEEDS", "PROJECT_EXPANSION"], is_for_new_unit: false, key_benefit_keywords: ["SECURED_AGAINST_ASSETS", "LONG_TENURE"], loan_type: "OTHER", max_tenure_yrs: 10 },
  // GOVT SCHEMES
  { scheme_name: "ESDP (Skill Development)", loan_type: "TRAINING_GRANT", target_demographics: ["SC_ST_PROMOTER", "WOMAN_PROMOTER", "DIFFERENTLY_ABLED", "BPL_PERSONS"], target_sectors: ["ALL"], target_purpose: ["SKILL_DEVELOPMENT", "ENTREPRENEURSHIP_PROMOTION"], is_for_new_unit: null, key_benefit_keywords: ["FREE_TRAINING", "STIPEND"], is_grant_scheme: true },
  { scheme_name: "MSME Cluster Development", loan_type: "GRANT_INFRASTRUCTURE", max_amount_cr: 20.0, target_demographics: ["SPV_OR_GOVT"], target_sectors: ["MANUFACTURING", "SERVICE"], target_purpose: ["INFRASTRUCTURE_DEVELOPMENT", "COMMON_FACILITY_CENTRE"], is_for_new_unit: null, key_benefit_keywords: ["GOVT_GRANT", "CAPITAL_SUBSIDY_UP_TO_70%"], is_grant_scheme: true },
  { scheme_name: "Procurement & Marketing Support", loan_type: "SUBSIDY_MARKETING", target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["MARKETING_ASSISTANCE", "EXHIBITION_PARTICIPATION"], is_for_new_unit: null, key_benefit_keywords: ["SUBSIDY", "TRADE_FAIR_SUPPORT"], is_grant_scheme: true },
  { scheme_name: "CGTMSE", loan_type: "GUARANTEE_COVER", min_amount_cr: 0.01, max_amount_cr: 5.0, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["LOAN_GUARANTEE", "CAPITAL_LOAN", "WORKING_CAPITAL_LOAN"], is_for_new_unit: null, key_benefit_keywords: ["COLLATERAL_FREE_LOAN", "GUARANTEE_COVERAGE"], is_grant_scheme: true },
  { scheme_name: "CLCSS (Tech Upgradation)", loan_type: "SUBSIDY_CAPEX", min_amount_cr: 0.01, max_amount_cr: 1.0, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE"], target_purpose: ["TECHNOLOGY_UPGRADATION", "CAPEX_MACHINERY_ACQUISITION"], is_for_new_unit: null, key_benefit_keywords: ["CAPITAL_SUBSIDY", "MODERNIZATION"], is_grant_scheme: true },
  { scheme_name: "PMEGP", loan_type: "SUBSIDY_CUM_LOAN", max_amount_cr: 0.5, target_demographics: ["ALL"], target_sectors: ["MANUFACTURING", "SERVICE"], target_purpose: ["PROJECT_SETUP", "EMPLOYMENT_GENERATION"], is_for_new_unit: true, key_benefit_keywords: ["SUBSIDY_UP_TO_35%", "LOAN_ASSISTANCE"], is_grant_scheme: true },
  { scheme_name: "MUDRA Yojana", loan_type: "LOAN", min_amount_cr: 0.01, max_amount_cr: 0.1, target_demographics: ["ALL"], target_sectors: ["ALL"], target_purpose: ["PROJECT_SETUP", "WORKING_CAPITAL_GENERAL"], is_for_new_unit: null, key_benefit_keywords: ["MICRO_FINANCE", "SHISHU_KISHOR_TARUN"], is_grant_scheme: false },
  { scheme_name: "Stand Up India", loan_type: "LOAN", min_amount_cr: 0.1, max_amount_cr: 10.0, target_demographics: ["SC_ST_PROMOTER", "WOMAN_PROMOTER"], target_sectors: ["ALL"], target_purpose: ["PROJECT_SETUP", "GREENFIELD_PROJECTS"], is_for_new_unit: true, key_benefit_keywords: ["SC_ST_WOMEN_FOCUS", "GREENFIELD_PROJECTS"], is_grant_scheme: false, max_tenure_yrs: 7 },
  { scheme_name: "ZED Certification", loan_type: "SUBSIDY_QUALITY", target_demographics: ["ALL"], target_sectors: ["MANUFACTURING"], target_purpose: ["QUALITY_CERTIFICATION", "ENVIRONMENTAL_COMPLIANCE"], is_for_new_unit: null, key_benefit_keywords: ["ZED_CERTIFICATION", "SUBSIDY_ON_CONSULTANCY"], is_grant_scheme: true },
  { scheme_name: "ASPIRE (Rural Innovation)", loan_type: "SUBSIDY_INCUBATION", target_demographics: ["ALL"], target_sectors: ["RURAL_INDUSTRY", "INNOVATION_STARTUPS"], target_purpose: ["INCUBATION", "LIVELIHOOD_MISSION"], is_for_new_unit: true, key_benefit_keywords: ["RURAL_FOCUS", "FUNDING_FOR_INCUBATORS"], is_grant_scheme: true }
];

export default SCHEMES_DATA;